### ISSUE TITLE
Criação do DAO para entidade Cidade método selecionar

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/redesocial#78]

**Comment by Ronneesley** [comment]
Agora o método selecionar() da classe CidadeDAO, caso queira continuar pontuando.

**Comment by WesleyMFelix** [comment]
Certo!

Em 9 de ago de 2017 12:03 PM, "Ronneesley Moura Teles" <
notifications@github.com> escreveu:

Agora o método selecionar() da classe CidadeDAO, caso queira continuar
pontuando.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/Ronneesley/redesocial/issues/78#issuecomment-321282922>,
or mute the thread

**Comment by WesleyMFelix** [comment]
Enviada!

**Comment by Ronneesley** [comment]
Está quase perfeito. Somente na chave estrangeira que o objeto que deveria ter sido criado era:
*EstadoDAO estadoDAO = new EstadoDAO();*
E na atribuição seria:
*p.setEstado(estadoDAO.selecionar(rs.getInt("estado")));*

Já fiz para ti. Considero a atividade encerrada.
